const GET_ALL_USERS = "Users:GET_ALL_USERS";
const GET_ALL_AGENTS = "admin:GET_ALL_AGENTS";
const ADD_AGENTS = "admin:ADD_AGENTS";
const DELETE_USERS = "Users:DELETE_USERS";
const UPDATE_USERS = "Users:UPDATE_USERS";
const DELETE_AGENT = "admin:DELETE_AGENT";
const UPDATE_AGENT = "admin:UPDATE_AGENT";


module.exports = { GET_ALL_USERS, GET_ALL_AGENTS, ADD_AGENTS, DELETE_USERS, UPDATE_USERS, DELETE_AGENT, UPDATE_AGENT };